### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by jmgomezpoveda** [SpoOkyMagician/spooky_default#22]
For a theme, it would be very interesting to link some screenshots from the README.md file.

**Comment by SpoOkyMagician** [comment]
Uh, I am still new to GitHub but, I will look into it...

**Comment by jmgomezpoveda** [comment]
I don't see any links in the main page (https://github.com/SpoOkyMagician/spooky_default). Did you commit and push your changes?

**Comment by SpoOkyMagician** [comment]
Check the raw file. It should be there... :\
